language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
branches:
  only:
  - master
script: npm test
deploy:
  provider: npm
  email: ask.colorfully.me@gmail.com
  api_key:
    secure: BQfs3FuBBiEj/WmT9wEIWUjPlE7KdIHearNb+Ukh8FLZ6ntNCLKTNGz8fdM1eB/kdonSyvysYNKa48hYzN7hzeq0Yyl75YtWzNYb3VbxIhAeNeee65rOY+moI4M/8oSTwDFiK7We456vDfOzGFdm2IHEl0emCyI/bYl8mNgHPuk=
  on:
    branch: master
    repo: ColorfullyMe/idol-client
